### ISSUE TITLE
Something similar using Maven and Cursive?

### ISSUE THREAD

**Issue by scotts777** [jayzawrotny/lein-rebl-example#1]
Thanks for the example.  I followed the same pattern as you provided to use rebl with a java based application that uses Clojure.   I have dependencies in my POM for nrepl and start a nrepl on application start-up over a certain port.

Typically, I connect to that nrepl just fine through IntelliJ/Cursive.  I added core.async and the REBL .jar to my POM and started the application.  I connected through the Cursive repl to my nrepl by port.  Then I required the namespace for repl and evaluated (rebl/ui).  The REBL interface loaded and came up.  I am able to type forms into the top left area and it works fine that way.

However when I enter forms into my Cursive repl window, they do not show up in REBL.  Any idea what I should be thinking about to make that connection happen?

Thanks again for getting me this far already

**Comment by visibletrap** [comment]
A workaround, you can call `(cognitect.rebl/inspect (your-expression))` to send your expression to rebl

**Comment by scotts777** [comment]
thanks visibletrap, that isn't too bad.  Appreciate that.

**Comment by jaidetree** [comment]
I am glad this was helpful to you. To my knowledge running REBL directly like this prevents it from receiving all expressions sent to a REPL.

This may be good feedback to provide to Cognitect through the official [REBL repo issues](https://github.com/cognitect-labs/REBL-distro/issues) as feedback so they can think about adding a means for it or better communicate why.

Though if that functionality is worth it to you, I think it may be possible by creating some [nrepl-middleware](https://nrepl.xyz/nrepl/design/middleware.html) that sends each form sent to the REPL to `(cognitect.rebl/inspect)` as visibletrap has shared.

**Comment by DaveWM** [comment]
@scotts777 I had the same problem as you, and wrote some nrepl middleware like @jayzawrotny suggested. If you're interested, it's here: https://github.com/DaveWM/nrepl-rebl

**Comment by jaidetree** [comment]
@DaveWM Very nice! I'm trying to polish another person's nrepl-rebl middleware in a pull request https://github.com/jayzawrotny/nrebl.middleware.
